### PR TITLE
Support same field name in DB and in model

### PR DESCRIPTION
**Pull request by fcarreiro**
Support same field name in DB and in model

See issue #1

### CODE REVIEW

**Comment by fcarreiro** [comment]
@joshswan sorry it took so long, here it is! (I ran it against my project and it seems to be working).

**Comment by joshswan** [comment]
Looks awesome. I'll cut a new version shortly

**Comment by fcarreiro** [comment]
Great! Let me know so that I can replace my customized plugin in one of my projects 👍

**Comment by joshswan** [comment]
Just published `v0.2.2`. Thanks again!

**Pull request merged**
